---
deployment:
  tasks:
    - export DEPLOYPATH="$HOME/public_html"
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "$DEPLOYPATH/assets"
    - /bin/cp -R assets "$DEPLOYPATH/assets"
    - /bin/cp about.html "$DEPLOYPATH/about.html"
    - /bin/cp country.html "$DEPLOYPATH/country.html"
    - /bin/cp enquiry.html "$DEPLOYPATH/enquiry.html"
    - /bin/cp index.html "$DEPLOYPATH/index.html"
    - /bin/cp international-driving-license.html "$DEPLOYPATH/international-driving-license.html"
    - /bin/cp privacy.html "$DEPLOYPATH/privacy.html"
    - /bin/cp robots.txt "$DEPLOYPATH/robots.txt"
    - /bin/cp terms.html "$DEPLOYPATH/terms.html"
    - /bin/cp thank-you.html "$DEPLOYPATH/thank-you.html"
    - /bin/cp visas.html "$DEPLOYPATH/visas.html"
    - /bin/cp whatsapp.html "$DEPLOYPATH/whatsapp.html"
    - /bin/cp android-chrome-192x192.png "$DEPLOYPATH/android-chrome-192x192.png"
    - /bin/cp android-chrome-512x512.png "$DEPLOYPATH/android-chrome-512x512.png"
    - /bin/cp apple-touch-icon.png "$DEPLOYPATH/apple-touch-icon.png"
    - /bin/cp favicon-16x16.png "$DEPLOYPATH/favicon-16x16.png"
    - /bin/cp favicon-32x32.png "$DEPLOYPATH/favicon-32x32.png"
    - /bin/cp favicon.ico "$DEPLOYPATH/favicon.ico"
    - /bin/cp site.webmanifest "$DEPLOYPATH/site.webmanifest"
    - /bin/rm -f "$DEPLOYPATH/netlify.toml" "$DEPLOYPATH/sitemap.xml"
